# Generated by Django 3.2.12 on 2022-03-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gwcbsvertragposten",
            name="sparte",
            field=models.ForeignKey(
                db_column="sparte_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracting.gwcbsvertragpostensparten",
            ),
        ),
    ]
