# Generated by Django 3.2.12 on 2022-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0003_alter_gwcbsvertragposten_sparte"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="fullfillment_datacenter",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="contract",
            name="salesforce_record",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.IntegerField(default=99, verbose_name="status"),
        ),
        migrations.AddField(
            model_name="contractclient",
            name="easybill_url",
            field=models.URLField(default="https://easybill.de"),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="kpi_kva",
            field=models.IntegerField(default=0, verbose_name="KPI value kva"),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="kpi_kwh",
            field=models.IntegerField(default=0, verbose_name="KPI value kwh"),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="kpi_sqm",
            field=models.IntegerField(default=0, verbose_name="KPI value sqm"),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="kpi_type",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="KPI value type"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="salesforce_record",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="fullfillment_datacenter",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="salesforce_record",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="status",
            field=models.IntegerField(default=99, verbose_name="status"),
        ),
        migrations.AddField(
            model_name="historicalcontractclient",
            name="easybill_url",
            field=models.URLField(default="https://easybill.de"),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="kpi_kva",
            field=models.IntegerField(default=0, verbose_name="KPI value kva"),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="kpi_kwh",
            field=models.IntegerField(default=0, verbose_name="KPI value kwh"),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="kpi_sqm",
            field=models.IntegerField(default=0, verbose_name="KPI value sqm"),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="kpi_type",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="KPI value type"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="salesforce_record",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="contract",
            name="billing_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="billing_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="contract_item_type",
            field=models.IntegerField(
                choices=[
                    [3, "once"],
                    [1, "recuring_fixed"],
                    [2, "recuring_variable"],
                    [9, "unknown"],
                ],
                verbose_name="contract item type",
            ),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="cost_center",
            field=models.IntegerField(default=0, verbose_name="cost center"),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="customer_description",
            field=models.TextField(
                blank=True, default="", verbose_name="customer description"
            ),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="included_power",
            field=models.BigIntegerField(default=0, verbose_name="included power"),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="net_price",
            field=models.DecimalField(
                decimal_places=7, default=0, max_digits=15, verbose_name="net price"
            ),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="valid from"),
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="valid_till",
            field=models.DateField(blank=True, null=True, verbose_name="valid till"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="billing_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="billing_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="contract_item_type",
            field=models.IntegerField(
                choices=[
                    [3, "once"],
                    [1, "recuring_fixed"],
                    [2, "recuring_variable"],
                    [9, "unknown"],
                ],
                verbose_name="contract item type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="cost_center",
            field=models.IntegerField(default=0, verbose_name="cost center"),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="customer_description",
            field=models.TextField(
                blank=True, default="", verbose_name="customer description"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="included_power",
            field=models.BigIntegerField(default=0, verbose_name="included power"),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="net_price",
            field=models.DecimalField(
                decimal_places=7, default=0, max_digits=15, verbose_name="net price"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="valid from"),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="valid_till",
            field=models.DateField(blank=True, null=True, verbose_name="valid till"),
        ),
    ]
