# Generated by Django 3.2.12 on 2022-03-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0004_auto_20220322_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gwcbsbuchungskontotransaktionen",
            name="datum_buchungstag",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gwcbsbuchungskontotransaktionen",
            name="datum_erstellt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gwcbsbuchungskontotransaktionen",
            name="datum_wertstellung",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gwcbsrechnungen",
            name="transaction",
            field=models.ForeignKey(
                db_column="transaction_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracting.gwcbsbuchungskontotransaktionen",
            ),
        ),
    ]
