# Generated by Django 3.2.12 on 2022-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0006_auto_20220412_0501"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="last_invoice_override",
            field=models.DateField(
                blank=True,
                help_text="Set this field to change the next invoice starting date, e.g. because there have been credits to this account.",
                null=True,
                verbose_name="Last invoice (override)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="last_invoice_override",
            field=models.DateField(
                blank=True,
                help_text="Set this field to change the next invoice starting date, e.g. because there have been credits to this account.",
                null=True,
                verbose_name="Last invoice (override)",
            ),
        ),
    ]
