# Generated by Django 3.2.12 on 2022-04-13 11:29

import contracting.utils.easybill
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0007_contract_item_last_invoice_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="state",
        ),
        migrations.AddField(
            model_name="bookingaccount",
            name="easybill_data",
            field=models.JSONField(default=contracting.utils.easybill.get_default_data),
        ),
        migrations.AddField(
            model_name="bookingaccount",
            name="easybill_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingaccount",
            name="easybill_sync_state",
            field=models.CharField(
                choices=[
                    ("unsynced", "no initial sync"),
                    ("dirty", "not in sync"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="easybill_data",
            field=models.JSONField(default=contracting.utils.easybill.get_default_data),
        ),
        migrations.AddField(
            model_name="customer",
            name="easybill_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="easybill_sync_state",
            field=models.CharField(
                choices=[
                    ("unsynced", "no initial sync"),
                    ("dirty", "not in sync"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="easybill_data",
            field=models.JSONField(default=contracting.utils.easybill.get_default_data),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="easybill_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="easybill_sync_state",
            field=models.CharField(
                choices=[
                    ("unsynced", "no initial sync"),
                    ("dirty", "not in sync"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="easybill_data",
            field=models.JSONField(default=contracting.utils.easybill.get_default_data),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="easybill_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="easybill_sync_state",
            field=models.CharField(
                choices=[
                    ("unsynced", "no initial sync"),
                    ("dirty", "not in sync"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="easybill_data",
            field=models.JSONField(default=contracting.utils.easybill.get_default_data),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="easybill_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="easybill_sync_state",
            field=models.CharField(
                choices=[
                    ("unsynced", "no initial sync"),
                    ("dirty", "not in sync"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="easybill_data",
            field=models.JSONField(default=contracting.utils.easybill.get_default_data),
        ),
        migrations.AddField(
            model_name="transaction",
            name="easybill_sync_state",
            field=models.CharField(
                choices=[
                    ("unsynced", "no initial sync"),
                    ("dirty", "not in sync"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
    ]
