# Generated by Django 3.2.12 on 2022-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0008_easybill_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingaccount",
            name="invoice_delivery",
        ),
        migrations.RemoveField(
            model_name="historicalbookingaccount",
            name="invoice_delivery",
        ),
        migrations.AddField(
            model_name="bookingaccount",
            name="invoice_delivery_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookingaccount",
            name="invoice_delivery_post",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="invoice_delivery_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="invoice_delivery_post",
            field=models.BooleanField(default=False),
        ),
    ]
