# Generated by Django 3.2.12 on 2022-04-20 01:34

import contracting.models.customer
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0009_invoice_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingaccount",
            name="easybill_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="crm_data",
            field=models.JSONField(
                default=contracting.models.customer.get_default_data
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="crm_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="easybill_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="easybill_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="crm_data",
            field=models.JSONField(
                default=contracting.models.customer.get_default_data
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="crm_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="easybill_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="easybill_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="easybill_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
