# Generated by Django 3.2.12 on 2022-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0010_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="easybill_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
