# Generated by Django 3.2.12 on 2022-04-28 09:48

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0011_transaction_easybill_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccount",
            name="tax_rate",
            field=models.DecimalField(
                choices=[(Decimal("19"), "19"), (Decimal("0"), "0")],
                decimal_places=1,
                default="19",
                max_digits=4,
                verbose_name="Tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbookingaccount",
            name="tax_rate",
            field=models.DecimalField(
                choices=[(Decimal("19"), "19"), (Decimal("0"), "0")],
                decimal_places=1,
                default="19",
                max_digits=4,
                verbose_name="Tax rate",
            ),
        ),
    ]
