# Generated by Django 3.2.12 on 2022-05-01 23:30

import contracting.models.invoice
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0012_auto_20220429_0237"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=contracting.models.invoice.get_document_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="bookingaccount",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("SEPA", "SEPA direct debit"),
                    ("INVOICE", "Invoice"),
                    ("NONE", "No data (historic import)"),
                ],
                default="INVOICE",
                max_length=7,
                verbose_name="Account type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbookingaccount",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("SEPA", "SEPA direct debit"),
                    ("INVOICE", "Invoice"),
                    ("NONE", "No data (historic import)"),
                ],
                default="INVOICE",
                max_length=7,
                verbose_name="Account type",
            ),
        ),
    ]
