# Generated by Django 3.2.12 on 2022-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0013_auto_20220502_0130"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="pingen_data",
            field=models.JSONField(),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pingen_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pingen_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pingen_sync_state",
            field=models.CharField(
                choices=[("none", "not sent"), ("sent", "sent"), ("error", "error")],
                default="none",
                max_length=8,
            ),
        ),
    ]
