# Generated by Django 3.2.12 on 2022-05-02 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0012_auto_20220428_1148"),
        ("contracting", "0014_auto_20220502_0310"),
    ]

    operations = []
