# Generated by Django 3.2.12 on 2022-05-02 15:12

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0015_merge_0012_auto_20220428_1148_0014_auto_20220502_0310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccount",
            name="tax_option",
            field=models.CharField(
                choices=[
                    ("NULL", "Normal steuerbar"),
                    ("nStb", "Nicht steuerbar (Drittland)"),
                    ("nStbUstID", "Nicht steuerbar (EU mit USt-IdNr.)"),
                    ("nStbNoneUstId", "Nicht steuerbar (EU ohne USt-IdNr.)"),
                    ("nStbIm", "Nicht steuerbarer Innenumsatz"),
                    ("revc", "Steuerschuldwechsel §13b (Inland)"),
                    ("IG", "Innergemeinschaftliche Lieferung"),
                    ("AL", "Ausfuhrlieferung"),
                    ("sStfr", "sonstige Steuerbefreiung"),
                    ("small", "Kleinunternehmen (Keine MwSt.)"),
                ],
                default="NULL",
                max_length=13,
                verbose_name="Tax options",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbookingaccount",
            name="tax_option",
            field=models.CharField(
                choices=[
                    ("NULL", "Normal steuerbar"),
                    ("nStb", "Nicht steuerbar (Drittland)"),
                    ("nStbUstID", "Nicht steuerbar (EU mit USt-IdNr.)"),
                    ("nStbNoneUstId", "Nicht steuerbar (EU ohne USt-IdNr.)"),
                    ("nStbIm", "Nicht steuerbarer Innenumsatz"),
                    ("revc", "Steuerschuldwechsel §13b (Inland)"),
                    ("IG", "Innergemeinschaftliche Lieferung"),
                    ("AL", "Ausfuhrlieferung"),
                    ("sStfr", "sonstige Steuerbefreiung"),
                    ("small", "Kleinunternehmen (Keine MwSt.)"),
                ],
                default="NULL",
                max_length=13,
                verbose_name="Tax options",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="tax_rate",
            field=models.DecimalField(
                choices=[(Decimal("19"), "19"), (Decimal("0"), "0")],
                decimal_places=1,
                default="19",
                max_digits=4,
                verbose_name="Tax rate",
            ),
        ),
    ]
