# Generated by Django 3.2.12 on 2022-05-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0016_auto_20220502_1712"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingaccount",
            name="vat_id",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="order_reference",
        ),
        migrations.RemoveField(
            model_name="historicalbookingaccount",
            name="vat_id",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="order_reference",
        ),
        migrations.AlterField(
            model_name="bookingaccount",
            name="tax_option",
            field=models.CharField(
                choices=[
                    ("NULL", "Normal steuerbar"),
                    ("nStb", "Nicht steuerbar (Drittland)"),
                    ("nStbUstID", "Nicht steuerbar (EU mit USt-IdNr.)"),
                    ("nStbNoneUstID", "Nicht steuerbar (EU ohne USt-IdNr.)"),
                    ("nStbIm", "Nicht steuerbarer Innenumsatz"),
                    ("revc", "Steuerschuldwechsel §13b (Inland)"),
                    ("IG", "Innergemeinschaftliche Lieferung"),
                    ("AL", "Ausfuhrlieferung"),
                    ("sStfr", "sonstige Steuerbefreiung"),
                    ("smallBusiness", "Kleinunternehmen (Keine MwSt.)"),
                ],
                default="NULL",
                max_length=13,
                verbose_name="Tax options",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbookingaccount",
            name="tax_option",
            field=models.CharField(
                choices=[
                    ("NULL", "Normal steuerbar"),
                    ("nStb", "Nicht steuerbar (Drittland)"),
                    ("nStbUstID", "Nicht steuerbar (EU mit USt-IdNr.)"),
                    ("nStbNoneUstID", "Nicht steuerbar (EU ohne USt-IdNr.)"),
                    ("nStbIm", "Nicht steuerbarer Innenumsatz"),
                    ("revc", "Steuerschuldwechsel §13b (Inland)"),
                    ("IG", "Innergemeinschaftliche Lieferung"),
                    ("AL", "Ausfuhrlieferung"),
                    ("sStfr", "sonstige Steuerbefreiung"),
                    ("smallBusiness", "Kleinunternehmen (Keine MwSt.)"),
                ],
                default="NULL",
                max_length=13,
                verbose_name="Tax options",
            ),
        ),
    ]
