# Generated by Django 3.2.12 on 2022-05-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0017_auto_20220518_0342"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="contract_reference",
            new_name="order_reference",
        ),
        migrations.RenameField(
            model_name="historicalcontract",
            old_name="contract_reference",
            new_name="order_reference",
        ),
    ]
