# Generated by Django 3.2.12 on 2022-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0018_auto_20220518_0342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="order_reference",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="order reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="order_reference",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="order reference"
            ),
        ),
    ]
