# Generated by Django 3.2.12 on 2022-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0019_auto_20220518_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingaccount",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("zugferd2", "Zugferd 2"),
                    ("xrechnung_xml", "XRechnung (XML)"),
                ],
                default="zugferd2",
                max_length=14,
                verbose_name="Invoice type",
            ),
        ),
        migrations.AddField(
            model_name="bookingaccount",
            name="xrechnung_buyer_reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("zugferd2", "Zugferd 2"),
                    ("xrechnung_xml", "XRechnung (XML)"),
                ],
                default="zugferd2",
                max_length=14,
                verbose_name="Invoice type",
            ),
        ),
        migrations.AddField(
            model_name="historicalbookingaccount",
            name="xrechnung_buyer_reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
