# Generated by Django 3.2.12 on 2022-05-31 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0020_auto_20220531_1425"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="pingen_data",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="pingen_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="pingen_last_sync",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="pingen_sync_state",
        ),
    ]
