# Generated by Django 3.2.12 on 2022-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0021_auto_20220531_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="gnom_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="internal_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="network_information",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="gnom_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="internal_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="network_information",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
