# Generated by Django 3.2.12 on 2022-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0022_auto_20220623_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractitem",
            name="gnom_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontractitem",
            name="gnom_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
