# Generated by Django 3.2.12 on 2022-09-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0023_auto_20220623_1701"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractitem",
            options={
                "base_manager_name": "objects",
                "ordering": ("number",),
                "verbose_name": "Contract Item",
                "verbose_name_plural": "Contract Items",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontractitem",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Contract Item",
            },
        ),
        migrations.RemoveField(
            model_name="contractitem",
            name="location",
        ),
        migrations.RemoveField(
            model_name="historicalcontractitem",
            name="location",
        ),
        migrations.AddField(
            model_name="contract",
            name="special_conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="special conditions"
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_items",
                to="contracting.contractitem",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="realization_he",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="realization_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="realization_rack",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="realization_site",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="special_conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="special conditions"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contracting.contractitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="realization_he",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="realization_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="realization_rack",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="realization_site",
            field=models.TextField(blank=True, null=True),
        ),
    ]
