# Generated by Django 3.2.12 on 2022-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0024_new_contract_item_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="is_recurring",
            field=models.BooleanField(default=True),
        ),
    ]
