# Generated by Django 3.2.12 on 2022-09-22 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracting", "0025_invoiceitem_is_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitem",
            name="availability_guaranteed",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Guaranteed availability",
            ),
        ),
        migrations.AddField(
            model_name="contractitem",
            name="availability_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The interval for which availability is guaranteed. Put 8760 for a year, 720 for a month (30 days).",
                max_digits=6,
                null=True,
                verbose_name="Availability interval in hours",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="availability_guaranteed",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Guaranteed availability",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitem",
            name="availability_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The interval for which availability is guaranteed. Put 8760 for a year, 720 for a month (30 days).",
                max_digits=6,
                null=True,
                verbose_name="Availability interval in hours",
            ),
        ),
    ]
