# Generated by Django 3.2.24 on 2024-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracting", "0026_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccount",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("zugferd2_2", "Zugferd 2"),
                    ("xrechnung3_0_xml", "XRechnung (XML)"),
                ],
                default="zugferd2_2",
                max_length=16,
                verbose_name="Invoice type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbookingaccount",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("zugferd2_2", "Zugferd 2"),
                    ("xrechnung3_0_xml", "XRechnung (XML)"),
                ],
                default="zugferd2_2",
                max_length=16,
                verbose_name="Invoice type",
            ),
        ),
        migrations.RunSQL(
            """UPDATE contracting_bookingaccount
            SET invoice_type = 'zugferd2_2'
            WHERE invoice_type = 'zugferd2';

            UPDATE contracting_bookingaccount
            SET invoice_type = 'xrechnung3_0_xml'
            WHERE invoice_type = 'xrechnung_xml';"""
        ),
    ]
