# Generated by Django 3.2.12 on 2022-06-22 13:02

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "log_level",
                    models.IntegerField(
                        choices=[
                            ("50", "Critical"),
                            ("40", "Error"),
                            ("30", "Warning"),
                            ("20", "Info"),
                            ("10", "Debug"),
                        ],
                        default="10",
                    ),
                ),
                ("origin", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
