# Generated by Django 2.1.7 on 2019-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GwCbsBuchungskonto",
            fields=[
                (
                    "buchungskontoid",
                    models.AutoField(
                        db_column="buchungskontoId", primary_key=True, serialize=False
                    ),
                ),
                ("kundeid", models.PositiveIntegerField(db_column="kundeId")),
                ("active", models.CharField(max_length=1)),
                ("kontostand", models.FloatField()),
                ("zahlungsart", models.CharField(max_length=13)),
                ("zustellung", models.PositiveIntegerField()),
                ("zahlungsfrist", models.IntegerField()),
                ("mwst", models.CharField(max_length=1)),
                ("ust_id_nr", models.CharField(blank=True, max_length=32, null=True)),
                ("ueberweisungsfrist", models.IntegerField()),
                (
                    "gwkonto_dtaus_path",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("bemerkung", models.TextField(blank=True, null=True)),
                ("faelligkeitstyp", models.CharField(max_length=1)),
                ("old_gwkonto_id", models.PositiveIntegerField()),
                ("iban_elv_konto", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "field_elv_vorhanden",
                    models.IntegerField(db_column="_elv_vorhanden"),
                ),
                (
                    "ebics_account",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("creditor_id", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "invoice_approval_by",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "db_table": "gw_cbs_buchungskonto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwCbsBuchungskontoKonto",
            fields=[
                (
                    "kontoid",
                    models.AutoField(
                        db_column="kontoId", primary_key=True, serialize=False
                    ),
                ),
                ("inhaber", models.CharField(max_length=255)),
                ("kreditinstitut", models.CharField(max_length=255)),
                ("blz", models.CharField(max_length=100)),
                ("kontonummer", models.CharField(max_length=100)),
                ("geloescht", models.CharField(max_length=1)),
                ("notizen", models.TextField()),
            ],
            options={
                "db_table": "gw_cbs_buchungskonto_konto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwCbsBuchungskontoSepaelv",
            fields=[
                (
                    "buchungskonto_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("requested", models.DateTimeField(blank=True, null=True)),
                (
                    "request_document_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("confirmed", models.DateTimeField(blank=True, null=True)),
                (
                    "confirm_document_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("revoked", models.DateTimeField(blank=True, null=True)),
                (
                    "revoke_document_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("first_used", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("mandatstyp", models.CharField(max_length=6)),
                ("mandatsreferenz", models.CharField(max_length=35)),
                ("kreditinstitut", models.CharField(max_length=64)),
                ("bic", models.CharField(max_length=11)),
                ("iban", models.CharField(max_length=34)),
                ("kontoinhaber", models.CharField(max_length=150)),
                ("anschrift", models.CharField(max_length=150)),
                ("plz", models.CharField(max_length=20)),
                ("ort", models.CharField(max_length=100)),
                ("bundesland", models.CharField(max_length=100)),
                ("land", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "gw_cbs_buchungskonto_sepaelv",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwCbsVertrag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_id", models.PositiveIntegerField(blank=True, null=True)),
                ("firma", models.PositiveIntegerField()),
                ("projekt", models.CharField(max_length=16)),
                (
                    "created_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "modified_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "midwife_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "provision_customer_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ticket_id", models.PositiveIntegerField(blank=True, null=True)),
                ("vname", models.CharField(max_length=100)),
                ("kommentar", models.TextField()),
                (
                    "kunden_referenz_nummer",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("erstellt", models.DateTimeField()),
                ("beginn", models.DateField()),
                ("letzte_rechnung", models.DateField()),
                ("letzte_aenderung", models.DateTimeField()),
                ("ende", models.DateField()),
                ("ausgelaufen", models.IntegerField()),
                (
                    "ausgelaufen_ticket_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("naechste_rechnung", models.DateField()),
                ("frist", models.DateField()),
                ("rechnungsintervall", models.IntegerField()),
                ("kuend_frist", models.IntegerField()),
                ("beginn_laufzeit", models.PositiveIntegerField()),
                ("verlaengerung", models.IntegerField()),
                ("rechnungsintervall_anpassung", models.PositiveIntegerField()),
                ("rechnungsende_anpassung", models.PositiveIntegerField()),
                ("zuletzt_gedruckt", models.DateField()),
                ("unterzeichnet", models.IntegerField()),
                ("unterzeichnet_am", models.DateField()),
                ("gekuendigt", models.IntegerField()),
                ("gekuendigt_am", models.DateTimeField()),
                (
                    "gekuendigt_ticket_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "gekuendigt_kundenticket_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("anlagen", models.CharField(max_length=255)),
                ("t_vertrag_name", models.CharField(max_length=255)),
                ("t_vertrag_beschr", models.CharField(max_length=255)),
                ("t_postenbez", models.CharField(max_length=255)),
                (
                    "gw_iz_privileges_realm_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("freigeschalten", models.IntegerField()),
                ("freigeschalten_am", models.DateTimeField()),
                ("suspended", models.PositiveIntegerField()),
                (
                    "suspended_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("einzelrechnung", models.PositiveIntegerField()),
                (
                    "alte_vertragsnummer_gwag",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "gw_cbs_vertrag",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwCbsVertragPosten",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.PositiveIntegerField()),
                ("vorlageid", models.IntegerField()),
                ("reihenfolge", models.IntegerField()),
                ("typ", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=60)),
                ("beschreibung", models.TextField()),
                ("preis", models.FloatField()),
                (
                    "gw_dsl_public_ippool_ip",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "gw_dsl_public_subnetpool_net",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("freitraffic", models.PositiveIntegerField()),
                ("abgerechnet", models.CharField(max_length=1)),
                (
                    "abgerechnetam",
                    models.DateField(blank=True, db_column="abgerechnetAm", null=True),
                ),
                ("subnet_size", models.PositiveIntegerField()),
                ("vpn_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gw_ppp_accounts_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "gw_ip_subnets_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("gw_nodes_id", models.PositiveIntegerField(blank=True, null=True)),
                ("sparte_id", models.IntegerField(blank=True, null=True)),
                (
                    "field_sparte_id",
                    models.PositiveIntegerField(
                        blank=True, db_column="_sparte_id", null=True
                    ),
                ),
                (
                    "tixi_device_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "tixi_anpassungsposition_eeg2014",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cs_building_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "easybill_product_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "gw_cbs_vertrag_posten",
                "managed": False,
            },
        ),
    ]
