# Generated by Django 2.1.7 on 2019-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwCbsVertragPostenSparten",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("fibu_konto", models.IntegerField()),
                ("gruppe", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=8)),
                (
                    "midwife_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
            ],
            options={
                "db_table": "gw_cbs_vertrag_posten_sparten",
                "managed": False,
            },
        ),
    ]
