# Generated by Django 2.1.7 on 2019-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0002_gwcbsvertragpostensparten"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwCbsVertragPostenEasybillprodukte",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("cost_price", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "export_cost1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "export_cost2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "export_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "export_identifier_extended",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("group_id", models.CharField(blank=True, max_length=255, null=True)),
                ("login_id", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("price_type", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.CharField(blank=True, max_length=255, null=True)),
                ("sale_price", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sale_price2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price6",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price8",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price9",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sale_price10",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stock", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stock_count",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stock_limit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stock_limit_notify",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "vat_percent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "gw_cbs_vertrag_posten_easybillprodukte",
                "managed": False,
            },
        ),
    ]
