# Generated by Django 2.2.7 on 2019-11-22 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0003_gwcbsvertragposteneasybillprodukte"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GwCbsVertragPostenSparten",
        ),
    ]
