# Generated by Django 2.2.7 on 2019-11-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0004_delete_gwcbsvertragpostensparten"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwAamLieferschein",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "gw_aam_lieferschein",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwAamLieferscheinPosten",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorlage_id", models.PositiveIntegerField(null=True)),
                ("reihenfolge", models.PositiveIntegerField(null=True)),
                ("typ", models.CharField(blank=True, max_length=255, null=True)),
                ("von", models.DateField(null=True)),
                ("bis", models.DateField(null=True)),
                ("anzahl", models.FloatField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("beschreibung", models.TextField()),
                ("optionen", models.CharField(blank=True, max_length=255, null=True)),
                ("preis", models.FloatField()),
            ],
            options={
                "db_table": "gw_aam_lieferschein_posten",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwAamVorgang",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "gw_aam_vorgang",
                "managed": False,
            },
        ),
    ]
