# Generated by Django 2.2.7 on 2019-12-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0005_gwaamlieferschein_gwaamlieferscheinposten_gwaamvorgang"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwCbsCreditmemos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(null=True)),
                ("modified", models.DateTimeField(null=True)),
                (
                    "created_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "modified_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("credit_invoice_item_id", models.IntegerField(null=True)),
                ("debit_invoice_item_id", models.IntegerField(null=True)),
                ("billing_not_before", models.DateField(null=True)),
                ("approved", models.DateTimeField(null=True)),
                (
                    "approved_user_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("ticket_id", models.IntegerField(null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("von", models.DateField(db_column="from", null=True)),
                ("bis", models.DateField(db_column="to", null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.FloatField()),
                ("price", models.FloatField()),
                ("reason", models.TextField()),
            ],
            options={
                "db_table": "gw_cbs_creditmemos",
                "managed": False,
            },
        ),
    ]
