# Generated by Django 2.2.7 on 2019-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0006_gwcbscreditmemos"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwCbsRechnungen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kundeid", models.IntegerField()),
                ("transaction_id", models.IntegerField()),
                ("state_id", models.IntegerField()),
                ("datum", models.DateTimeField(null=True)),
                ("zahlungsziel", models.DateField(null=True)),
                ("betrag", models.FloatField()),
                ("mwst", models.FloatField()),
            ],
            options={
                "db_table": "gw_cbs_rechnungen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GwCbsRechnungenPositionen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(null=True)),
                ("typ", models.CharField(blank=True, max_length=255, null=True)),
                ("von", models.DateField(null=True)),
                ("bis", models.DateField(null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("beschreibung", models.TextField()),
                ("anzahl", models.FloatField()),
                ("preis", models.FloatField()),
                (
                    "referenztyp",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("referenz", models.IntegerField()),
            ],
            options={
                "db_table": "gw_cbs_rechnungen_positionen",
                "managed": False,
            },
        ),
    ]
