# Generated by Django 2.2.7 on 2020-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0007_gwcbsrechnungen_gwcbsrechnungenpositionen"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwCbsBuchungskontoTransaktionen",
            fields=[
                (
                    "transaktionid",
                    models.AutoField(
                        db_column="transaktionId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "buchungskontoid",
                    models.PositiveIntegerField(db_column="buchungskontoId"),
                ),
                ("betrag", models.FloatField()),
                ("bezahlt", models.FloatField()),
                ("art", models.CharField(max_length=5)),
                (
                    "sepa_transaction_type",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("datum_erstellt", models.DateTimeField()),
                ("datum_buchungstag", models.DateField()),
                ("datum_wertstellung", models.DateTimeField()),
                ("verwendungszweck", models.CharField(max_length=255)),
                ("datum_dtaus", models.DateTimeField(blank=True, null=True)),
                ("datum_rueckbuchung", models.DateTimeField(blank=True, null=True)),
                ("tracking_id", models.CharField(max_length=16)),
                (
                    "ebics_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ebics_payment_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "ebics_statuscode",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "ebics_statusreasoncode",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("bezahlt_tmp", models.FloatField(db_column="bezahlt_TMP")),
                ("hbcilog", models.TextField()),
                ("sepa1810dup", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "gw_cbs_buchungskonto_transaktionen",
                "managed": False,
            },
        ),
    ]
