# Generated by Django 2.2.7 on 2020-02-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gwdb", "0008_gwcbsbuchungskontotransaktionen"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwZustellung",
            fields=[
                (
                    "zustellungid",
                    models.AutoField(
                        db_column="zustellungId", primary_key=True, serialize=False
                    ),
                ),
                ("zustellung_email", models.CharField(max_length=1)),
                ("zustellung_post", models.CharField(max_length=1)),
                ("zustellung_per_hand", models.CharField(max_length=1)),
                ("zustellung_email_an", models.CharField(max_length=255)),
                ("zustellung_post_an", models.TextField()),
                ("zustellung_per_hand_an", models.CharField(max_length=255)),
                ("zugestellt_email_am", models.DateTimeField(blank=True, null=True)),
                ("zugestellt_post_am", models.DateTimeField(blank=True, null=True)),
                ("zugestellt_per_hand_am", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "gw_zustellung",
                "managed": False,
            },
        ),
    ]
