# Generated by Django 2.1.7 on 2019-09-24 14:00

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import globalways.models.globalways_tool
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("globalways", "0002_gitcommit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDeployment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "sha",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="commit"
                    ),
                ),
                (
                    "deployment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="deployment date",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="globalways_servicedeployment_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="globalways_servicedeployment_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Git Commit",
                "verbose_name_plural": "Git Commits",
                "ordering": ["sha"],
            },
            bases=(globalways.models.globalways_tool.GlobalwaysTool, models.Model),
        ),
    ]
