# Generated by Django 2.1.7 on 2019-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0003_servicedeployment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicedeployment",
            options={
                "ordering": ["sha"],
                "verbose_name": "service deployment",
                "verbose_name_plural": "service deployment",
            },
        ),
    ]
