# Generated by Django 2.2.7 on 2020-01-31 16:28

import celery.app.task
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0004_auto_20190924_1609"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetryTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=255, verbose_name="task name"),
                ),
                (
                    "send_task_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="send task data"
                    ),
                ),
                (
                    "last_try",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last try"
                    ),
                ),
                ("try_count", models.IntegerField(default=0, verbose_name="try count")),
            ],
            bases=(models.Model, celery.app.task.Task),
        ),
    ]
