# Generated by Django 2.2.7 on 2020-01-31 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0005_retrytask"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retrytask",
            options={
                "ordering": ("-last_try",),
                "verbose_name": "retry task",
                "verbose_name_plural": "retry tasks",
            },
        ),
    ]
