# Generated by Django 2.2.7 on 2020-01-31 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0006_auto_20200131_1744"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RetryTask",
        ),
    ]
