# Generated by Django 2.2.7 on 2020-02-07 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0008_retrytaskstate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retrytaskstate",
            options={
                "ordering": ("-last_try",),
                "verbose_name": "retry task state",
                "verbose_name_plural": "retry task states",
            },
        ),
    ]
