# Generated by Django 2.2.7 on 2020-08-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0010_activediretoryguidprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activedirectoryguidprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="globalways_activedirectoryguidprofile_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activedirectoryguidprofile",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="globalways_activedirectoryguidprofile_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
