# Generated by Django 3.2.12 on 2022-03-27 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0013_auto_20211117_1602"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cspreport",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="cspreport",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="cspreport",
            name="user",
        ),
        migrations.RemoveField(
            model_name="gitcommit",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="gitcommit",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="reviewstate",
            name="change_request",
        ),
        migrations.RemoveField(
            model_name="reviewstate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reviewstate",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="servicedeployment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="servicedeployment",
            name="modified_by",
        ),
        migrations.DeleteModel(
            name="ChangeRequest",
        ),
        migrations.DeleteModel(
            name="CSPReport",
        ),
        migrations.DeleteModel(
            name="GitCommit",
        ),
        migrations.DeleteModel(
            name="ReviewState",
        ),
        migrations.DeleteModel(
            name="ServiceDeployment",
        ),
    ]
