# Generated by Django 3.2.12 on 2022-06-22 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0014_auto_20220327_0432"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RetryTaskState",
        ),
    ]
