# Generated by Django 3.2.12 on 2022-06-22 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globalways", "0015_delete_retrytaskstate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActiveDirectoryGuidProfile",
        ),
    ]
