name: Code Style

on:
  push:
    branches: [ gw ]
  pull_request:
    branches: [ gw ]
  workflow_dispatch:
    inputs: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run isort
        run: poetry run isort -c .
  flake:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run flake8
        run: poetry run flake8 .
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run black
        run: poetry run black --check .
  djhtml:
    name: djhtml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run djhtml
        run: 'poetry run djhtml ccdb/'
